version = "3.9.4"
runner.dialect = scala3
maxColumn = 100
align.preset = more
docstrings.style = Asterisk
rewrite.rules = [RedundantBraces, RedundantParens]
rewrite.scala3.convertToNewSyntax = true
rewrite.scala3.removeOptionalBraces = false
