blueprint {
  name = {{name}}
  streamlets {
    echo = {{name}}
  }
  topics {
    # Written by something outside the pipeline, so not managed: the platform only consumes it.
    input {
      managed           = false
      topic.name        = "{{name}}.input"
      bootstrap.servers = "kafka:9092"
      consumers         = [echo.in]
    }
    # Managed: the operator creates it. Kafka name defaults to {{name}}.output.
    output {
      producers  = [echo.out]
      partitions = 3
      replicas   = 1
    }
  }
}
